version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    hostname: postgres
    env_file:
      - .env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
  web:
    env_file:
      - .env
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - database
volumes:
    database-data: # named volumes can be managed easier using docker-compose
