# Generated by Django 3.1.4 on 2021-04-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_grading'),
    ]

    operations = [
        migrations.AddField(
            model_name='grading',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
