# Generated by Django 3.2 on 2021-04-24 14:46

import django.contrib.postgres.fields.ranges
import django.contrib.postgres.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='age_range',
            field=django.contrib.postgres.fields.ranges.IntegerRangeField(default='(1, 18)', validators=[django.contrib.postgres.validators.RangeMinValueValidator(1), django.contrib.postgres.validators.RangeMaxValueValidator(18)]),
        ),
    ]
