# Generated by Django 3.2 on 2021-04-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_stockitem_age_range'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockitem',
            old_name='grading',
            new_name='quality',
        ),
        migrations.AddField(
            model_name='stockitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
