# Generated by Django 3.2 on 2021-04-25 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20210424_1453'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grading',
            new_name='Quality',
        ),
    ]
