# Generated by Django 3.2 on 2021-04-25 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_rename_type_stockitem_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Category',
        ),
    ]
