# Generated by Django 3.2 on 2021-04-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20210425_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='barcode',
            field=models.BigIntegerField(default=0),
        ),
    ]
