# Generated by Django 3.2 on 2021-04-25 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20210425_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='barcode',
        ),
    ]
