# Generated by Django 3.2 on 2021-04-25 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_stockitem_barcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockitem',
            name='barcode',
        ),
    ]
