# Generated by Django 3.2 on 2021-04-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_rename_stockitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.ImageField(default='default.png', upload_to='barcodes/'),
        ),
    ]
